### ISSUE TITLE
Respect Retry-After when rate limited by Spotify

### ISSUE THREAD

**Issue by billybednar** [svr333/audio-band#10]
Unfortunately Spotify does not have a public API designed for retrieving real-time playback status despite years of requests. AudoBand instead uses polling and apparently it is fairly easy to get rate limited. I tried reducing the polling interval to somewhere around 3x a second and quickly found myself blocked and with a several hundred megabyte log file. According to the [API documentation](https://developer.spotify.com/documentation/web-api/#rate-limiting), rate limiting is applied per application so theoretically one could also run into it with the default 1 second interval when using the same client id on 3 computers.

Spotify supposedly includes a `Retry-After` header on the 429 rate limit response and the Spotify API library [appears to make it available](https://github.com/JohnnyCrazy/SpotifyAPI-NET/blob/master/SpotifyAPI.Web/Exceptions/APITooManyRequestsException.cs). `SpotifyAudioSource.GetPlayback` should handle the `APITooManyRequestsException` exception and wait for the specified time (or a reasonable period if not specified).

Here is a stack trace of the rate limit getting hit for reference:
```
SpotifyAPI.Web.APITooManyRequestsException: Exception of type 'SpotifyAPI.Web.APITooManyRequestsException' was thrown.
   at SpotifyAPI.Web.Http.APIConnector.ProcessErrors(IResponse response)
   at SpotifyAPI.Web.Http.APIConnector.<DoRequest>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAPI.Web.Http.APIConnector.<DoSerializedRequest>d__30`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAPI.Web.Http.APIConnector.<SendAPIRequest>d__34`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SpotifyAudioSource.SpotifyAudioSource.<GetPlayback>d__102.MoveNext() in C:\Users\vanro\Documents\Programming\cs\audio-band\src\SpotifyAudioSource\SpotifyAudioSource.cs:line 512
```

**Comment by svr333** [comment]
Thank you for the information, are you looking to implement this yourself or should I go for it whenever I have the time?

**Comment by billybednar** [comment]
Not any time soon. Feel free to take it.
