### ISSUE TITLE
InvalidOperationException during album art update

### ISSUE THREAD

**Issue by billybednar** [svr333/audio-band#9]
## Description
Explorer unexpected crashed and the AudioBand toolbar disappeared.

## How To Reproduce
Unsure. Audio source is Windows 10 and idle profile is enabled (although it should not have triggered).

## Version
 - Windows 10 Pro 21H1 Build 19043.1165
 - AudioBand 0.9.9

## Logs
```
2021-08-22 22:58:02.0237|ERROR|AudioBand|Unhandled Exception
---START OF EXCEPTION---
System.InvalidOperationException: Object is currently in use elsewhere.

---END OF EXCEPTION---
---ORIGINAL EXCEPTION---
System.InvalidOperationException: Object is currently in use elsewhere.
   at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at AudioBand.Extensions.ImageExtensions.ToImageSource(Image image) in C:\Users\vanro\Documents\Programming\cs\audio-band\src\AudioBand\Extensions\ImageExtensions.cs:line 23
   at AudioBand.UI.AlbumArtViewModel.AlbumArtUpdated(Image albumArt) in C:\Users\vanro\Documents\Programming\cs\audio-band\src\AudioBand\UI\AlbumArt\AlbumArtViewModel.cs:line 106
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at AudioBand.ObservableObject.SetProperty[T](T& field, T newValue, String propertyName) in C:\Users\vanro\Documents\Programming\cs\audio-band\src\AudioBand\ObservableObject.cs:line 70
   at AudioBand.AudioSource.AudioSession.AudioSourceOnTrackInfoChanged(Object sender, TrackInfoChangedEventArgs e) in C:\Users\vanro\Documents\Programming\cs\audio-band\src\AudioBand\AudioSource\AudioSession.cs:line 179
   at AudioBand.AudioSource.AudioSourceProxy.<CreateWrapper>b__72_1(TrackInfoChangedEventArgs e) in C:\Users\vanro\Documents\Programming\cs\audio-band\src\AudioBand\AudioSource\AudioSourceProxy.cs:line 359
   at AudioSourceHost.MarshaledEventHandler`1.Handler(Object sender, T args)
   at Win10AudioSource.Win10AudioSource.<UpdateMediaProperties>d__51.MoveNext() in C:\Users\vanro\Documents\Programming\cs\audio-band\src\Win10AudioSource\Win10AudioSource.cs:line 240
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Win10AudioSource.Win10AudioSource.<CurrentSessionOnMediaPropertiesChanged>d__47.MoveNext() in C:\Users\vanro\Documents\Programming\cs\audio-band\src\Win10AudioSource\Win10AudioSource.cs:line 192
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
---END OF ORIGINAL EXCEPTION
```

**Comment by svr333** [comment]
Interesting, I think I have an idea of where it comes from though so I'll do some testing later on

**Comment by svr333** [comment]
Issue still persists, I'll have to find out how to fix it
